### ISSUE TITLE
Search tips screen needs CSS touchup

### ISSUE THREAD

**Issue by slknight** [CARLI/vufind#60] opened 2016-06-03 19:08 UTC
https://vufind3-test.carli.illinois.edu/vf-eiu/Help/Home?topic=search

Content is floated right, title and table are left aligned. Looks weird on my giant monitor.

**Comment by eschell** [comment] 2016-06-20 15:09
The problem is in the css .Content definition. The width and padding-left should be corrected. This will bring the right content up to top align with the left (but not the h1 that starts the page).

This should fix it:
.Content {
  float:right;
  padding-left:1%;
  width:67%;
}

I'm not sure where this page is coming from. This page doesn't go through the templeting system, so making a change in the carli.css will not work.

If you want a different layout altogether I'd first have to know where the page is coming from.

**Comment by cedelis** [comment] 2016-06-20 15:28
Page source says:
https://vufind3-devel.carli.illinois.edu/vf-eiu/themes/bootprint3/css/help.css?_=1464116696

which should be in the local file:

/usr/local/vufind/themes/bootprint3/css/help.css

which can be overriden in:

/usr/local/vufind/themes/carli/css/help.css

**Comment by cedelis** [comment] 2016-06-20 15:41
I made the change in -devel.

**Comment by eschell** [comment] 2016-06-20 15:53
If you want I made some further changes to a number of styles in the 

/usr/local/vufind/themes/carli/css/help.css

I also updated

/usr/local/vufind/themes/carli/theme.config.php 

to add the help.css to the template.

**Comment by gibsonjc** [comment] 2016-06-22 21:01
vufind3-test and vufind3-devel look better to me now. The table "table of contents" on the left and the actual content lined up at the top on the right.
https://vufind3-devel.carli.illinois.edu/vf-eiu/Help/Home?topic=search
https://vufind3-test.carli.illinois.edu/vf-eiu/Help/Home?topic=search

I am not sure why test is "fixed" if the change was made on devel?

Go ahead and move it to vufind3 (prod) whenever.  (not a high priority)

**Comment by gibsonjc** [comment] 2017-05-12 13:38
Closing; done on all servers.

**Closed by gibsonjc** 2017-05-12 13:38 UTC
Labels: Accepted, Ready for Prod
