### ISSUE TITLE
Non-Circ Item is Requestable

### ISSUE THREAD

**Issue by spicer66** [CARLI/vufind#291] opened 2018-01-23 20:17 UTC
It appears Special Collections items with "Non-Circulating" status are requestable in VuFind4.

Here is an example title for a Special Collections item from UIC:

Children of the settlement houses

https://i-share.carli.illinois.edu/all/vf-uic/Record/279971794

**Comment by katieediger** [comment] 2018-01-23 21:18
It could be an issue with the matrix entries. Check out https://github.com/CARLI/vufind/issues/262 

We (at IIT) noticed that some of our reserve items were suddenly requestable in VuFind 4 (that weren't requestable in .6). It turned out that we had UB turned on for some roles/ item types in the matrix. It hadn't been a problem in VuFind .6 because if charge/renew and UB were selected for an item type (but not call slip) those items still couldn't be requested.

**Comment by spicer66** [comment] 2018-01-23 22:04
Thanks Katie,

Someone here checked our matrix and reported back:

"Doesn’t seem to be the problem.  NOCIR item type isn’t configured in the matrix and the (all) (all) catch-all entry only has charge/renew checked."

**Comment by dmcmpbll** [comment] 2018-01-23 22:11
Hi @spicer66, I just sent an email to Gwen @ UIC- she'd submitted a ticket through support@carli.illinois.edu.
The example item is shelved in a location that falls under the Main Reference Group policy definition's set of matrix entries, rather than those in the Main policy definition.

The issue that @katieediger tagged is the cause for that item. I forwarded Gwen a list of the matrix entries in that policy definition for the NOCIR items and recommend unchecking both the Charge/Renew and the UB checkboxes, if the items are truly non-circulating.

**Comment by gibsonjc** [comment] 2018-01-24 19:18
Duplicate issue to #262 ; closing.

**Closed as completed by gibsonjc** 2018-01-24 19:18 UTC
Labels: duplicate
