### ISSUE TITLE
Default Search "Local Catalog Only"

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#69] opened 2016-06-06 18:14 UTC
UIS - Could our local catalog be set as the default?

**Comment by bgant** [comment] 2016-06-06 18:44
EIU - When I chose Eastern, I expected to be able to search in my local catalog

**Comment by gibsonjc** [comment] 2016-06-08 15:54
This is a duplicate of #40 ; comments have been moved there.

**Closed by gibsonjc** 2016-06-08 15:54 UTC
Labels: duplicate
