### ISSUE TITLE
"Recently Received Issues" Display even when MFHD is suppressed from OPAC

### ISSUE THREAD

**Issue by jenhm** [CARLI/vufind#369] opened 2018-08-16 17:36 UTC
SIC - Reported in RT 100915. It appears that if a MFHD is suppressed the details of the MFHD (like Location and Call number) do not display, but the Label "Most recently Received Issues": and any issues checked in via Acquisitions client Serials Check in and set to "Display in OPAC"=YES WILL Display (for an example see https://i-share-test.carli.illinois.edu/vf-ctu/Record/CTUdb.87517)

![image](https://user-images.githubusercontent.com/20780451/44224646-b02d1400-a150-11e8-8af5-b124c4d30e28.png)

My example above has 3 MFHDs:
Main Stacks, Bethany Stacks, and Current Periodicals.

The MFHD for Current Periodicals is suppressed but the checked in issue "no. 2" is set to Display in OPAC, so it is, even though the MFHD is not.

Here are some examples from the RT ticket from SIC, since they have some other scenarios, for other types of titles besides basic journal issues:

Traditionally in our workflow we have created Acquisitions check-in records for some titles in the Voyager Cataloging client. When items are received with that title, we check them in in the Voyager Acquisitions Client. The holdings and bib records in the cataloging client are suppressed so the check in record was not displayed in the online catalog. Now with the new Vu-Find interface our check in records are displaying. Is there any way to suppress that? Here is an example:
Marion Daily Republican; Bib #1093437
https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.1093437

We also use this process for titles of a series that we catalog individually. We are having the same problem with these.
Regnum vegetabile; Bib #1532453 (I suppressed the bib on this to see if that would make a difference)
https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.1532453
and
Ergebnisse der Mathematik und ihrer Grenzgebiete; Bib7004 (I left this one as is with just the holdings suppressed)
https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.7004

This one has a suppressed holdings records, but also has other holdings. The suppressed holdings is allowing the checked in items to display as "most recent received issues" like the other examples.
Geological Survey special report; Bib #1460319
https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.1460319

**Comment by gibsonjc** [comment] 2018-10-02 19:51
Problem statement: If a MFHD is suppressed in Voyager, the details of the MFHD (like Location and Call number) do not display, just as one would expect; however, any issues checked in via Acquisitions client > Serials Check In and set to "Display in OPAC=YES" DO display in the Holdings Tab in New VuFind under the label "Most Recently Received Issues".

Expected behavior: If a MFHD is suppressed, any issues checked in via Acquisitions client > Serials Check In and set to "Display in OPAC=YES" **should not** display in the New VuFind Holdings Tab.  (Note: Setting these items to "Display in OPAC=NO" in the Acquisitions client does remove the checked-in items from display, but this is not a feasible workaround because many libraries have many suppressed MFHD's with checked-in items set as "Display in OPAC=YES".)

Examples:
https://i-share-test.carli.illinois.edu/vf-sic/Record/SICdb.1460319
https://i-share-test.carli.illinois.edu/vf-sic/Record/SICdb.7004
https://i-share-test.carli.illinois.edu/vf-sic/Record/SICdb.1532453

https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.1033987 (has some on suppressed MFHD and some on unsuppressed MFHD)

**Comment by cedelis** [comment] 2018-10-03 20:43
@gibsonjc @fellowsgl @jenhm 

Below is the SQL VuFind uses to gather this data (e.g., SICdb.1460319).

Does anyone know how (or if it's possible) to modify it to suit our needs?

select
 LINE_ITEM_COPY_STATUS.MFHD_ID,
 SERIAL_ISSUES.ENUMCHRON from SICDB.SERIAL_ISSUES,
 SICDB.COMPONENT,
 SICDB.ISSUES_RECEIVED,
 SICDB.SUBSCRIPTION,
 SICDB.LINE_ITEM,
 SICDB.LINE_ITEM_COPY_STATUS
where
 SERIAL_ISSUES.COMPONENT_ID = COMPONENT.COMPONENT_ID
 and ISSUES_RECEIVED.ISSUE_ID = SERIAL_ISSUES.ISSUE_ID
 and ISSUES_RECEIVED.COMPONENT_ID = COMPONENT.COMPONENT_ID
 and COMPONENT.SUBSCRIPTION_ID = SUBSCRIPTION.SUBSCRIPTION_ID
 and SUBSCRIPTION.LINE_ITEM_ID = LINE_ITEM.LINE_ITEM_ID
 and LINE_ITEM_COPY_STATUS.LINE_ITEM_ID = LINE_ITEM.LINE_ITEM_ID
 and SERIAL_ISSUES.RECEIVED > 0
 and ISSUES_RECEIVED.OPAC_SUPPRESSED = 1
 and LINE_ITEM.BIB_ID = 1460319
order by
 LINE_ITEM_COPY_STATUS.MFHD_ID,
 SERIAL_ISSUES.ISSUE_ID DESC;

**Comment by fellowsgl** [comment] 2018-10-03 22:00
I think this should work (three added lines):


select
LINE_ITEM_COPY_STATUS.MFHD_ID,
SERIAL_ISSUES.ENUMCHRON

from

SICDB.SERIAL_ISSUES,
SICDB.COMPONENT,
SICDB.ISSUES_RECEIVED,
SICDB.SUBSCRIPTION,
SICDB.LINE_ITEM,
SICDB.LINE_ITEM_COPY_STATUS,

SICDB.MFHD_MASTER  <-------------Added line
where
SERIAL_ISSUES.COMPONENT_ID = COMPONENT.COMPONENT_ID
and ISSUES_RECEIVED.ISSUE_ID = SERIAL_ISSUES.ISSUE_ID
and ISSUES_RECEIVED.COMPONENT_ID = COMPONENT.COMPONENT_ID
and COMPONENT.SUBSCRIPTION_ID = SUBSCRIPTION.SUBSCRIPTION_ID
and SUBSCRIPTION.LINE_ITEM_ID = LINE_ITEM.LINE_ITEM_ID
and LINE_ITEM_COPY_STATUS.LINE_ITEM_ID = LINE_ITEM.LINE_ITEM_ID

and LINE_ITEM_COPY_STATUS.MFHD_ID = MFHD_MASTER.MFHD_ID  <-----------------Added line

and MFHD_MASTER.SUPPRESS_IN_OPAC = ‘N’                                    <----------------------- Added line
and SERIAL_ISSUES.RECEIVED > 0
and ISSUES_RECEIVED.OPAC_SUPPRESSED = 1
and LINE_ITEM.BIB_ID = 1460319
order by
LINE_ITEM_COPY_STATUS.MFHD_ID,
SERIAL_ISSUES.ISSUE_ID DESC;

**Comment by cedelis** [comment] 2018-10-04 16:30
I've made the changes above to the SQL. In TEST.

**Comment by gibsonjc** [comment] 2018-10-05 18:41
Looks good, Ready for Prod

**Comment by cedelis** [comment] 2018-10-08 16:24
In PROD

**Closed as completed by cedelis** 2018-10-08 16:24 UTC
Labels: Accepted, priority issue
