### ISSUE TITLE
Institutions with & in I-Share Narrow Search list display &amp; 

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#170] opened 2017-04-17 20:25 UTC
The & character isn't displaying properly:

![screen shot 2017-04-17 at 3 22 22 pm](https://cloud.githubusercontent.com/assets/17598357/25103403/0de5d058-2382-11e7-96dc-f18636412e06.png)

**Comment by cedelis** [comment] 2018-01-24 19:52
This is ready for testing

**Comment by dmcmpbll** [comment] 2018-01-24 21:01
![image](https://user-images.githubusercontent.com/20848151/35356726-dca63be0-0116-11e8-8dd4-6c40dc96f76d.png)

On I-Share-test I did a search for "cat" and then sorted the institutional facet by alphabetical so that I could check the names of IMS and LAC; they had ampersands as anticipated. (https://i-share-test.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=cat&type=AllFields)

**Comment by dmcmpbll** [comment] 2018-01-24 21:04
Making a note that the menu where you select the Pick-Up Library must be populated by different data because in that list, LAC has the word "and" instead of an ampersand.

LAC in pick-up lib list (word "and"): 
![image](https://user-images.githubusercontent.com/20848151/35356996-b881d408-0117-11e8-9fbf-bd177a86dded.png)

LAC in the facet list (ampersand):
![image](https://user-images.githubusercontent.com/20848151/35357039-d7c737fe-0117-11e8-89e6-5773b457ed30.png)

**Comment by gibsonjc** [comment] 2018-01-24 23:22
Yes, this fix is ready for Prod.  (Pick-up Library list problem which I also saw is new Issue which I have made: #292 .)

**Comment by cedelis** [comment] 2018-01-25 18:42
In production. Closing Issue.

**Comment by gibsonjc** [comment] 2018-07-19 14:42
The problem with  displaying the ampersand for LAC and IMS is back again in the Institution facet.  Reopening this Issue.
![screen shot 2018-07-19 at 9 40 11 am](https://user-images.githubusercontent.com/17598357/42949703-f679e318-8b37-11e8-965f-7ba5e1c0de2a.png)

**Comment by cedelis** [comment] 2018-08-16 14:51
@gibsonjc I cannot reproduce this today.

**Closed as completed** 2018-08-21 14:23 UTC
Labels: Accepted, priority issue, could be simple
