### ISSUE TITLE
Similar Items tab

### ISSUE THREAD

**Issue by slknight** [CARLI/vufind#58] opened 2016-06-03 18:49 UTC
Similar Items tab at bottom of record only displays text on mouse over. When no cover images are available, this feature appears to be broken. Ideally, cover image should be suppressed and text displayed if no cover image is available.

**Comment by bgant** [comment] 2016-06-06 18:05
"Me Too" from UIS: 

When looking at an individual record the “Similar Items” tab isn’t very useful because no images are being displayed.

**Comment by bgant** [comment] 2016-06-06 19:04
EIU - What is this [Similar Items] supposed to do?

**Comment by slknight** [comment] 2016-06-06 19:46
Honestly, I don't know why the "similar items" tab duplicates the "similar items" right panel. I'd be happy to see the tab disappear.

**Comment by bgant** [comment] 2016-06-14 19:28
I'm marking this as Inactive until we get Syndetics enabled and remove the "No Image Found" image.

**Comment by gibsonjc** [comment] 2017-06-22 19:54
ONU- “Similar items” tab is really cool—especially when cover image is available!

**Comment by gibsonjc** [comment] 2017-08-02 17:28
We decided to turn off the Similar Items tab with book carousel for now.

**Comment by gibsonjc** [comment] 2017-12-15 15:28
TIU - 12/14/2017 open call

**Comment by gibsonjc** [comment] 2017-12-19 18:06
LFC - 12/15/2017 open call

**Comment by gibsonjc** [comment] 2018-02-21 14:13
I confirmed with Demian via the email list on Feb. 16, 2018 that this is currently the best way to hide a tab like Similar Items:

> There is a section in module.config.php which controls this:
>  
> https://github.com/vufind-org/vufind/blob/master/module/VuFind/config/module.config.php#L598
>  
> If you want to disable a tab, you can add a parallel array structure inside your local module, but map the tab name to null instead of to a service name.
>  
> I apologize for the fact that setting up that array structure can be a bit troublesome ? this is probably something we should address through a new code generator in the near future.
>  
> Please let me know if you still need more help!
>  
> - Demian

**Comment by cedelis** [comment] 2018-02-21 15:11
Ready for Testing

**Comment by gibsonjc** [comment] 2018-02-21 16:14
@cedelis I'm glad you knew what Demian was talking about!  :-)

Similar Items tab is appropriately gone from /vf-xxx/
https://i-share-test.carli.illinois.edu/vf-eiu/Record/EIUdb.1106653
and appropriately gone from /all/vf-xxx/
https://i-share-test.carli.illinois.edu/all/vf-eiu/Record/274291074
but still showing in /all/vf/ -- can we get this one removed as well?
https://i-share-test.carli.illinois.edu/all/vf/Record/274291074

(Similar Items list on the sidebar is correctly unaffected.)

**Comment by cedelis** [comment] 2018-02-21 16:31
@gibsonjc Good catch. My 'clear cache' script was skipping all/vf/ (and vf/). I've updated my script and have cleared out the server-side cache objects. Now, the all/vf/ instance is up-to-date with the new Record Tab definitions, i.e., the Similar Items tab is gone now.

**Comment by gibsonjc** [comment] 2018-02-21 18:53
That did it, the Similar Items tab is now appropriately gone everywhere! Ready for Prod!

**Comment by gibsonjc** [comment] 2018-02-26 15:38
In prod 2/23. Closing.

**Closed by gibsonjc** 2018-02-26 15:38 UTC
Labels: Accepted, Ready for Prod, could be simple
